return {
    mod_name = {
        en = "Kill Icon",
        ja = "キルアイコン",
        ko = "킬 아이콘",
        ["zh-cn"] = "击杀图标",
        ["zh-tw"] = "擊殺圖示",
        ru = "Иконка убийства",
    },
    mod_description = {
        en = "Display kill icons on enemy kills.",
        ja = "敵を倒した際にキルアイコンを表示します。",
        ko = "적 처치 시 킬 아이콘을 표시합니다.",
        ["zh-cn"] = "在击杀敌人时显示击杀图标。",
        ["zh-tw"] = "在擊殺敵人時顯示擊殺圖示。",
        ru = "Отображать иконку убийства при убийстве врагов.",
    },
    -- Master switch
    enabled = {
        en = "Master Switch",
        ja = "マスタースイッチ",
        ko = "마스터 스위치",
        ["zh-cn"] = "总开关",
        ["zh-tw"] = "總開關",
        ru = "Главный переключатель",
    },
    -- Companion switch
    companion_kill_icon_enabled = {
        en = "Enable Companion Kill Icon",
        ja = "仲間のキルアイコンを有効化",
        ko = "동료 킬 아이콘 활성화",
        ["zh-cn"] = "启用伙伴击杀图标",
        ["zh-tw"] = "啟用夥伴擊殺圖示",
        ru = "Включить иконку убийства напарника",
    },
    -- Group titles
    general_settings = {
        en = "General Settings",
        ja = "一般設定",
        ko = "일반 설정",
        ["zh-cn"] = "通用设置",
        ["zh-tw"] = "一般設定",
        ru = "Общие настройки",
    },
    icon_settings = {
        en = "Icon Settings",
        ja = "アイコン設定",
        ko = "아이콘 설정",
        ["zh-cn"] = "图标设置",
        ["zh-tw"] = "圖示設定",
        ru = "Настройки иконки",
    },
    -- Kill icon settings
    kill_icon_enabled = {
        en = "Enable Kill Icon",
        ja = "キルアイコンを有効化",
        ko = "킬 아이콘 활성화",
        ["zh-cn"] = "启用击杀图标",
        ["zh-tw"] = "啟用擊殺圖示",
        ru = "Включить иконку убийства",
    },
    kill_target = {
        en = "Kill Icon Target",
        ja = "キルアイコンの対象",
        ko = "킬 아이콘 대상",
        ["zh-cn"] = "击杀图标生效对象",
        ["zh-tw"] = "擊殺圖示生效對象",
        ru = "Цель иконки убийства",
    },
    kill_dot_icon = {
        en = "Show Kill Icon on DoT Kills",
        ja = "継続ダメージキル時にアイコンを表示",
        ko = "도트 데미지 킬 시 아이콘 표시",
        ["zh-cn"] = "持续伤害击杀显示图标",
        ["zh-tw"] = "持續傷害擊殺顯示圖示",
        ru = "Показывать иконку при убийстве от урона во времени",
    },
    kill_icon_transparency = {
        en = "Kill Icon Transparency",
        ja = "キルアイコンの透明度",
        ko = "킬 아이콘 투명도",
        ["zh-cn"] = "击杀图标透明度",
        ["zh-tw"] = "擊殺圖示透明度",
        ru = "Прозрачность иконки убийства",
    },
    kill_icon_normal_color_r = {
        en = "Normal Icon Color - Red",
        ja = "通常アイコンの色 - 赤",
        ko = "일반 아이콘 색상 - 빨강",
        ["zh-cn"] = "普通图标颜色 - 红",
        ["zh-tw"] = "普通圖示顏色 - 紅",
        ru = "Цвет обычной иконки - Красный",
    },
    kill_icon_normal_color_g = {
        en = "Normal Icon Color - Green",
        ja = "通常アイコンの色 - 緑",
        ko = "일반 아이콘 색상 - 초록",
        ["zh-cn"] = "普通图标颜色 - 绿",
        ["zh-tw"] = "普通圖示顏色 - 綠",
        ru = "Цвет обычной иконки - Зелёный",
    },
    kill_icon_normal_color_b = {
        en = "Normal Icon Color - Blue",
        ja = "通常アイコンの色 - 青",
        ko = "일반 아이콘 색상 - 파랑",
        ["zh-cn"] = "普通图标颜色 - 蓝",
        ["zh-tw"] = "普通圖示顏色 - 藍",
        ru = "Цвет обычной иконки - Синий",
    },
    kill_icon_headshot_color_r = {
        en = "Headshot Icon Color - Red",
        ja = "ヘッドショットアイコンの色 - 赤",
        ko = "헤드샷 아이콘 색상 - 빨강",
        ["zh-cn"] = "爆头图标颜色 - 红",
        ["zh-tw"] = "爆頭圖示顏色 - 紅",
        ru = "Цвет иконки хедшота - Красный",
    },
    kill_icon_headshot_color_g = {
        en = "Headshot Icon Color - Green",
        ja = "ヘッドショットアイコンの色 - 緑",
        ko = "헤드샷 아이콘 색상 - 초록",
        ["zh-cn"] = "爆头图标颜色 - 绿",
        ["zh-tw"] = "爆頭圖示顏色 - 綠",
        ru = "Цвет иконки хедшота - Зелёный",
    },
    kill_icon_headshot_color_b = {
        en = "Headshot Icon Color - Blue",
        ja = "ヘッドショットアイコンの色 - 青",
        ko = "헤드샷 아이콘 색상 - 파랑",
        ["zh-cn"] = "爆头图标颜色 - 蓝",
        ["zh-tw"] = "爆頭圖示顏色 - 藍",
        ru = "Цвет иконки хедшота - Синий",
    },
    custom_hud_mode = {
        en = "Custom HUD Mode",
        ja = "Custom HUD モード",
        ko = "Custom HUD 모드",
        ["zh-cn"] = "Custom HUD 模式",
        ["zh-tw"] = "Custom HUD 模式",
        ru = "Режим Custom HUD",
    },
    custom_hud_mode_tooltip = {
        en = "Enable this option to allow the 「Custom HUD」 mod to manage the HUD layout.",
        ja = "このオプションを有効化すると、「Custom HUD」モッドによるHUDレイアウトの管理を許可します。",
        ko = "이 옵션을 활성화하면 「Custom HUD」 모드가 HUD 레이아웃을 관리하도록 허용합니다.",
        ["zh-cn"] = "开启此选项可允许由“Custom HUD”模组管理HUD布局",
        ["zh-tw"] = "開啟此選項可允許由「Custom HUD」模組管理HUD佈局",
        ru = "Включите эту опцию, чтобы разрешить модулю «Custom HUD» управлять компоновкой HUD.",
    },
    kill_icon_vertical_position = {
        en = "Icon Vertical Position",
        ja = "アイコンの垂直位置",
        ko = "아이콘 수직 위치",
        ["zh-cn"] = "图标垂直位置",
        ["zh-tw"] = "圖示垂直位置",
        ru = "Вертикальное положение иконки",
    },
    kill_icon_horizontal_position = {
        en = "Icon Horizontal Position",
        ja = "アイコンの水平位置",
        ko = "아이콘 수평 위치",
        ["zh-cn"] = "图标水平位置",
        ["zh-tw"] = "圖示水平位置",
        ru = "Горизонтальное положение иконки",
    },
    kill_icon_size = {
        en = "Icon Size",
        ja = "アイコンサイズ",
        ko = "아이콘 크기",
        ["zh-cn"] = "图标大小",
        ["zh-tw"] = "圖示大小",
        ru = "Размер иконки",
    },
    kill_icon_duration = {
        en = "Icon Display Duration",
        ja = "アイコン表示時間",
        ko = "아이콘 표시 시간",
        ["zh-cn"] = "图标显示时长",
        ["zh-tw"] = "圖示顯示時長",
        ru = "Длительность показа иконки",
    },
    -- Target type options
    all = {
        en = "All Enemies",
        ja = "全ての敵",
        ko = "모든 적",
        ["zh-cn"] = "全部敌人",
        ["zh-tw"] = "全部敵人",
        ru = "Все враги",
    },
    elite = {
        en = "Elite Only",
        ja = "エリートのみ",
        ko = "엘리트만",
        ["zh-cn"] = "仅精英",
        ["zh-tw"] = "僅精英",
        ru = "Только элита",
    },
    special = {
        en = "Special Only",
        ja = "スペシャルのみ",
        ko = "스페셜만",
        ["zh-cn"] = "仅专家",
        ["zh-tw"] = "僅專家",
        ru = "Только спец",
    },
    elite_special_boss = {
        en = "Elite, Special and Boss",
        ja = "エリート、スペシャル、ボス",
        ko = "엘리트, 스페셜, 보스",
        ["zh-cn"] = "精英、专家和Boss",
        ["zh-tw"] = "精英、專家和Boss",
        ru = "Элита, спец и босс",
    },
}
