return {
    mod_name = {
        en = "Kill Icon",
        ja = "キルアイコン",
        ko = "킬 아이콘",
        ["zh-cn"] = "击杀图标",
        ["zh-tw"] = "擊殺圖示",
        ru = "Иконка убийства",
    },
    mod_description = {
        en = "Display kill icons on enemy kills.",
        ja = "敵を倒した際にキルアイコンを表示します。",
        ko = "적 처치 시 킬 아이콘을 표시합니다.",
        ["zh-cn"] = "在击杀敌人时显示击杀图标。",
        ["zh-tw"] = "在擊殺敵人時顯示擊殺圖示。",
        ru = "Отображать иконку убийства при убийстве врагов.",
    },
    -- Master switch
    enabled = {
        en = "Master Switch",
        ja = "マスタースイッチ",
        ko = "마스터 스위치",
        ["zh-cn"] = "总开关",
        ["zh-tw"] = "總開關",
        ru = "Главный переключатель",
    },
    -- Companion switch
    companion_kill_icon_enabled = {
        en = "Enable Companion Kill Icon",
        ja = "仲間のキルアイコンを有効化",
        ko = "동료 킬 아이콘 활성화",
        ["zh-cn"] = "启用伙伴击杀图标",
        ["zh-tw"] = "啟用夥伴擊殺圖示",
        ru = "Включить иконку убийства напарника",
    },
    companion_kill_icon_enabled_description = {
        en = "Show kill icons for kills made by your companion (e.g. Cyber-Mastiff).",
        ja = "仲間（例：サイバー・マスティフ）によるキル時にアイコンを表示します。",
        ko = "동료(예: 사이버 마스티프)의 처치에도 킬 아이콘을 표시합니다.",
        ["zh-cn"] = "伙伴（如智能獒犬）击杀时也显示图标。",
        ["zh-tw"] = "夥伴（如智能獒犬）擊殺時也顯示圖示。",
        ru = "Показывать иконку за убийства напарника (напр., кибермастиф).",
    },
    -- Group titles
    general_settings = {
        en = "General Settings",
        ja = "一般設定",
        ko = "일반 설정",
        ["zh-cn"] = "通用设置",
        ["zh-tw"] = "一般設定",
        ru = "Общие настройки",
    },
    icon_settings = {
        en = "Icon Settings",
        ja = "アイコン設定",
        ko = "아이콘 설정",
        ["zh-cn"] = "图标设置",
        ["zh-tw"] = "圖示設定",
        ru = "Настройки иконки",
    },
    -- Kill icon settings
    kill_icon_enabled = {
        en = "Enable Kill Icon",
        ja = "キルアイコンを有効化",
        ko = "킬 아이콘 활성화",
        ["zh-cn"] = "启用击杀图标",
        ["zh-tw"] = "啟用擊殺圖示",
        ru = "Включить иконку убийства",
    },
    kill_target = {
        en = "Kill Icon Target",
        ja = "キルアイコンの対象",
        ko = "킬 아이콘 대상",
        ["zh-cn"] = "击杀图标生效对象",
        ["zh-tw"] = "擊殺圖示生效對象",
        ru = "Цель иконки убийства",
    },
    kill_target_description = {
        en = "Select which enemy types display kill icons.",
        ja = "キルアイコンを表示する敵の種類を選択します。",
        ko = "킬 아이콘을 표시할 적 유형을 선택합니다.",
        ["zh-cn"] = "选择显示击杀图标的敌人类型。",
        ["zh-tw"] = "選擇顯示擊殺圖示的敵人類型。",
        ru = "Выберите, для каких типов врагов отображать иконки убийства.",
    },
    kill_dot_icon = {
        en = "Show Kill Icon on DoT Kills",
        ja = "継続ダメージキル時にアイコンを表示",
        ko = "도트 데미지 킬 시 아이콘 표시",
        ["zh-cn"] = "持续伤害击杀显示图标",
        ["zh-tw"] = "持續傷害擊殺顯示圖示",
        ru = "Показывать иконку при убийстве от урона во времени",
    },
    kill_dot_icon_description = {
        en = "Show kill icons for damage over time kills (bleeding, burning, toxin, etc.).",
        ja = "継続ダメージ（出血、燃焼、毒など）によるキル時にアイコンを表示します。",
        ko = "지속 피해(출혈, 화염, 독 등)로 처치 시 킬 아이콘을 표시합니다.",
        ["zh-cn"] = "持续伤害（流血、燃烧、毒素等）击杀时显示图标。",
        ["zh-tw"] = "持續傷害（流血、燃燒、毒素等）擊殺時顯示圖示。",
        ru = "Показывать иконку при убийстве от урона во времени (кровотечение, горение, токсин и т.д.).",
    },
    kill_icon_duration = {
        en = "Icon Display Duration",
        ja = "アイコン表示時間",
        ko = "아이콘 표시 시간",
        ["zh-cn"] = "图标显示时长",
        ["zh-tw"] = "圖示顯示時長",
        ru = "Длительность показа иконки",
    },
    kill_icon_duration_description = {
        en = "How long each kill icon stays on screen.",
        ja = "キルアイコンの表示時間。",
        ko = "킬 아이콘이 화면에 표시되는 시간.",
        ["zh-cn"] = "击杀图标在屏幕上的停留时长。",
        ["zh-tw"] = "擊殺圖示在畫面上的停留時長。",
        ru = "Как долго иконка убийства остаётся на экране.",
    },
    kill_icon_size = {
        en = "Icon Size",
        ja = "アイコンサイズ",
        ko = "아이콘 크기",
        ["zh-cn"] = "图标大小",
        ["zh-tw"] = "圖示大小",
        ru = "Размер иконки",
    },
    kill_icon_size_description = {
        en = "Kill icon size. 100% is the default size.",
        ja = "キルアイコンのサイズ。100%がデフォルトサイズです。",
        ko = "킬 아이콘 크기. 100%가 기본 크기입니다.",
        ["zh-cn"] = "击杀图标大小，100% 为默认大小。",
        ["zh-tw"] = "擊殺圖示大小，100% 為預設大小。",
        ru = "Размер иконки убийства. 100% — стандартный размер.",
    },
    kill_icon_spacing = {
        en = "Icon Spacing",
        ja = "アイコンの間隔",
        ko = "아이콘 간격",
        ["zh-cn"] = "图标间距",
        ["zh-tw"] = "圖示間距",
        ru = "Расстояние между иконками",
    },
    kill_icon_spacing_description = {
        en = "Spacing between kill icons. 100% is the default and maximum spacing; 50% is the minimum.",
        ja = "キルアイコン同士の間隔。100%がデフォルト（最大）の間隔で、50%が最小値です。",
        ko = "킬 아이콘 사이의 간격. 100%가 기본(최대) 간격이며, 50%가 최소값입니다.",
        ["zh-cn"] = "击杀图标之间的间距。100% 为默认（最大）间距，50% 为最小值。",
        ["zh-tw"] = "擊殺圖示之間的間距。100% 為預設（最大）間距，50% 為最小值。",
        ru = "Расстояние между иконками убийств. 100% — стандартный (максимальный) интервал; минимальное значение — 50%.",
    },
    kill_icon_transparency = {
        en = "Kill Icon Transparency",
        ja = "キルアイコンの透明度",
        ko = "킬 아이콘 투명도",
        ["zh-cn"] = "击杀图标透明度",
        ["zh-tw"] = "擊殺圖示透明度",
        ru = "Прозрачность иконки убийства",
    },
    kill_icon_transparency_description = {
        en = "Kill icon transparency. 100% is fully opaque.",
        ja = "キルアイコンの透明度。100%で完全不透明です。",
        ko = "킬 아이콘 투명도. 100%는 완전히 불투명합니다.",
        ["zh-cn"] = "击杀图标透明度，100% 为完全不透明。",
        ["zh-tw"] = "擊殺圖示透明度，100% 為完全不透明。",
        ru = "Прозрачность иконки убийства. 100% — полная непрозрачность.",
    },
    kill_icon_normal_color = {
        en = "Normal Icon Color",
        ja = "通常アイコンの色",
        ko = "일반 아이콘 색상",
        ["zh-cn"] = "普通图标颜色",
        ["zh-tw"] = "普通圖示顏色",
        ru = "Цвет обычной иконки",
    },
    kill_icon_headshot_color = {
        en = "Headshot Icon Color",
        ja = "ヘッドショットアイコンの色",
        ko = "헤드샷 아이콘 색상",
        ["zh-cn"] = "爆头图标颜色",
        ["zh-tw"] = "爆頭圖示顏色",
        ru = "Цвет иконки хедшота",
    },
    manage_icon_position = {
        en = "Use Built-in Icon Positioning",
        ja = "内蔵アイコン位置調整を使用",
        ko = "내장 아이콘 위치 조정 사용",
        ["zh-cn"] = "使用内置图标定位",
        ["zh-tw"] = "使用內建圖示定位",
        ru = "Использовать встроенное позиционирование иконки",
    },
    manage_icon_position_description = {
        en = "When enabled, the icon position is controlled by the settings below.\n\nDisable it to allow the 「Custom HUD」 mod to manage the HUD layout.",
        ja = "有効にすると、以下の設定でアイコンの位置を制御します。\n\n無効にすると、「Custom HUD」モッドによるHUDレイアウトの管理を許可します。",
        ko = "활성화하면 아래 설정으로 아이콘 위치를 제어합니다.\n\n비활성화하면 「Custom HUD」 모드가 HUD 레이아웃을 관리하도록 허용합니다.",
        ["zh-cn"] = "开启后将由下方设置控制图标位置。\n\n关闭此选项可允许由「Custom HUD」模组管理HUD布局。",
        ["zh-tw"] = "開啟後將由下方設定控制圖示位置。\n\n關閉此選項可允許由「Custom HUD」模組管理HUD佈局。",
        ru = "Когда включено, положение иконки определяется настройками ниже.\n\nОтключите, чтобы позволить модулю «Custom HUD» управлять компоновкой HUD.",
    },
    kill_icon_vertical_position = {
        en = "Icon Vertical Position",
        ja = "アイコンの垂直位置",
        ko = "아이콘 수직 위치",
        ["zh-cn"] = "图标垂直位置",
        ["zh-tw"] = "圖示垂直位置",
        ru = "Вертикальное положение иконки",
    },
    kill_icon_vertical_position_description = {
        en = "Vertical position of the icon area. 0% is the top of the screen, 100% is the bottom.",
        ja = "アイコン領域の垂直位置。0%が画面最上部、100%が最下部です。",
        ko = "아이콘 영역의 수직 위치. 0%가 화면 최상단, 100%가 최하단입니다.",
        ["zh-cn"] = "图标区域的垂直位置。0% 为屏幕顶部，100% 为底部。",
        ["zh-tw"] = "圖示區域的垂直位置。0% 為畫面頂部，100% 為底部。",
        ru = "Вертикальное положение области иконок. 0% — верх экрана, 100% — низ.",
    },
    kill_icon_horizontal_position = {
        en = "Icon Horizontal Position",
        ja = "アイコンの水平位置",
        ko = "아이콘 수평 위치",
        ["zh-cn"] = "图标水平位置",
        ["zh-tw"] = "圖示水平位置",
        ru = "Горизонтальное положение иконки",
    },
    kill_icon_horizontal_position_description = {
        en = "Horizontal position of the icon area. 0% is the left edge of the screen, 100% is the right.",
        ja = "アイコン領域の水平位置。0%が画面左端、100%が右端です。",
        ko = "아이콘 영역의 수평 위치. 0%가 화면 왼쪽, 100%가 오른쪽입니다.",
        ["zh-cn"] = "图标区域的水平位置。0% 为屏幕左边缘，100% 为右边缘。",
        ["zh-tw"] = "圖示區域的水平位置。0% 為畫面左緣，100% 為右緣。",
        ru = "Горизонтальное положение области иконок. 0% — левый край экрана, 100% — правый.",
    },
    -- Units
    percent = {
        en = "%%",
    },
    second = {
        en = "s",
        ja = "秒",
        ko = "초",
        ["zh-cn"] = "秒",
        ["zh-tw"] = "秒",
        ru = "с",
    },
    -- Target type options
    all = {
        en = "All Enemies",
        ja = "全ての敵",
        ko = "모든 적",
        ["zh-cn"] = "全部敌人",
        ["zh-tw"] = "全部敵人",
        ru = "Все враги",
    },
    elite = {
        en = "Elite Only",
        ja = "エリートのみ",
        ko = "엘리트만",
        ["zh-cn"] = "仅精英",
        ["zh-tw"] = "僅精英",
        ru = "Только элита",
    },
    special = {
        en = "Special Only",
        ja = "スペシャルのみ",
        ko = "스페셜만",
        ["zh-cn"] = "仅专家",
        ["zh-tw"] = "僅專家",
        ru = "Только спец",
    },
    elite_special_boss = {
        en = "Elite, Special and Boss",
        ja = "エリート、スペシャル、ボス",
        ko = "엘리트, 스페셜, 보스",
        ["zh-cn"] = "精英、专家和Boss",
        ["zh-tw"] = "精英、專家和Boss",
        ru = "Элита, спец и босс",
    },
}
